name: Test Runner

on:
  workflow_dispatch: # Manual trigger

jobs:
  test-job:
    runs-on: self-hosted 
    steps:
      - name: Verify Runner
        run: echo "This job is running on runner lx29."
